name: Check special events

on:
  pull_request:
    paths:
      - 'fortune_generator/json/custom_special.json'
      - 'fortune_generator/json/static_special.json'
      - 'fortune_generator/json/cyclical_special.json'

  push:
    paths:
      - 'fortune_generator/json/custom_special.json'
      - 'fortune_generator/json/static_special.json'
      - 'fortune_generator/json/cyclical_special.json'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Check Custom Special Events
        run: |
          python3 scripts/check-events.py fortune_generator/json/custom_special.json custom

      - name: Check Static Special Events
        run: |
          python3 scripts/check-events.py fortune_generator/json/static_special.json static

      - name: Check Cyclical Special Events
        run: |
          python3 scripts/check-events.py fortune_generator/json/cyclical_special.json cyclical
